html[0]="<!DOCTYPE html>"
html[1]="<html lang=\"en\">"
html[2]="  <head>"
html[3]="    <meta charset=\"utf-8\">"
html[4]="    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
html[5]="    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
html[6]=""
html[7]="    <title>ptt新聞</title>"
html[8]=""
html[9]=""
html[10]=""
html[11]="    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">"
html[12]="    <link href=\"css/style.css\" rel=\"stylesheet\">"
html[13]=""
html[14]="  </head>"
html[15]="  <body>"
html[16]=""
html[17]="    <div class=\"container-fluid\">"
html[18]="	<div class=\"row\">"
html[19]="		<div class=\"col-md-12\">"
html[20]="			<nav class=\"navbar navbar-default\" role=\"navigation\">"
html[21]="				<div class=\"navbar-header\">"
html[22]="					 "
html[23]="					<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">"
html[24]="						 <span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span>"
html[25]="					</button> <a class=\"navbar-brand\" href=\"#\">新聞產生器</a>"
html[26]="				</div>"
html[27]="				"
html[28]="				<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">"
html[29]="					<ul class=\"nav navbar-nav\">"
html[30]="						<li class=\"active\">"
html[31]="							<a href=\"index.html\">首頁</a>"
html[32]="						</li>"
html[33]="						"
html[34]="						<li class=\"dropdown\">"
html[35]="							 <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">其他版<strong class=\"caret\"></strong></a>"
html[36]="							<ul class=\"dropdown-menu\">"
html[37]="								<li>"
html[38]="									<a href=\"#\">八卦版</a>"
html[39]="								</li>"
html[40]="								<li>"
html[41]="									<a href=\"#\">表特版</a>"
html[42]="								</li>"
html[43]="								<li>"
html[44]="									<a href=\"#\">西施版</a>"
html[45]="								</li>"
html[46]="								"
html[47]="								<li class=\"divider\">"
html[48]="								</li>"
html[49]="								<li>"
html[50]="									<a href=\"https://www.ptt.cc/bbs/Gossiping/index.html\">ptt網站版</a>"
html[51]="								</li>"
html[52]="							</ul>"
html[53]="						</li>"
html[54]="					</ul>"
html[55]="					<form class=\"navbar-form navbar-left\" role=\"search\">"
html[56]="						<div class=\"form-group\">"
html[57]="							<input type=\"text\" class=\"form-control\">"
html[58]="						</div> "
html[59]="						<button type=\"submit\" class=\"btn btn-default\">"
html[60]="							搜尋"
html[61]="						</button>"
html[62]="					</form>"
html[63]="					"
html[64]="				</div>"
html[65]="				"
html[66]="			</nav>"
html[67]="			"
html[68]="			<div class=\"row\">"
html[69]="				<div class=\"col-md-4\">"
html[70]="				</div>"
html[71]="				<div class=\"col-md-4\">"
html[72]="					<div class=\"row\">"
html[73]="						<div class=\"col-md-4\">"
html[74]="							<div class=\"thumbnail\">"
html[75]="								<img alt=\"Bootstrap Thumbnail First\" src=\"https://i.imgur.com/WDNvmq9.jpg\">"
html[76]="								<div class=\"caption\">"
html[77]="									<h3>"
html[78]="										[正妹] 泱泱"
html[79]="									</h3>"
html[80]="									<p>"
html[81]="										有人直呼「有泱泱就推」，網友說「我老婆 請撤照 謝謝」，也有網友認為「我老婆 你有問過我嗎」"
html[82]="									</p>"
html[83]=""
html[84]="									<p>"
html[85]="										<a class=\"btn btn-primary\" href=\"web0.html\">點我看新聞</a>"
html[86]="									</p>"
html[87]="								</div>"
html[88]="							</div>"
html[89]="						</div>"
html[90]="						<div class=\"col-md-4\">"
html[91]="							<div class=\"thumbnail\">"
html[92]="								<img alt=\"Bootstrap Thumbnail Second\" src=\"https://i.imgur.com/KyvRPlG.jpg\">"
html[93]="								<div class=\"caption\">"
html[94]="									<h3>"
html[95]="										Thumbnail label"
html[96]="									</h3>"
html[97]="									<p>"
html[98]="										沒想到網友竟然"
html[99]="									</p>"
html[100]="									<p>"
html[101]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[102]="									</p>"
html[103]="								</div>"
html[104]="							</div>"
html[105]="						</div>"
html[106]="						<div class=\"col-md-4\">"
html[107]="							<div class=\"thumbnail\">"
html[108]="								<img alt=\"Bootstrap Thumbnail Third\" src=\"http://lorempixel.com/output/sports-q-c-600-200-1.jpg\">"
html[109]="								<div class=\"caption\">"
html[110]="									<h3>"
html[111]="										Thumbnail label"
html[112]="									</h3>"
html[113]="									"
html[114]="									<p>"
html[115]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[116]="									</p>"
html[117]="								</div>"
html[118]="							</div>"
html[119]="						</div>"
html[120]="					</div>"
html[121]="				</div>"
html[122]="				<div class=\"col-md-4\">"
html[123]="				</div>"
html[124]="			</div>"
html[125]=""
html[126]=""
html[127]="<div class=\"row\">"
html[128]="				<div class=\"col-md-4\">"
html[129]="				</div>"
html[130]="				<div class=\"col-md-4\">"
html[131]="					<div class=\"row\">"
html[132]="						<div class=\"col-md-4\">"
html[133]="							<div class=\"thumbnail\">"
html[134]="								<img alt=\"Bootstrap Thumbnail First\" src=\"http://lorempixel.com/output/people-q-c-600-200-1.jpg\">"
html[135]="								<div class=\"caption\">"
html[136]="									<h3>"
html[137]="										Thumbnail label"
html[138]="									</h3>"
html[139]="									<p>"
html[140]="										Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit."
html[141]="									</p>"
html[142]=""
html[143]="									<p>"
html[144]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[145]="									</p>"
html[146]="								</div>"
html[147]="							</div>"
html[148]="						</div>"
html[149]="						<div class=\"col-md-4\">"
html[150]="							<div class=\"thumbnail\">"
html[151]="								<img alt=\"Bootstrap Thumbnail Second\" src=\"https://i.imgur.com/KyvRPlG.jpg\">"
html[152]="								<div class=\"caption\">"
html[153]="									<h3>"
html[154]="										Thumbnail label"
html[155]="									</h3>"
html[156]="									<p>"
html[157]="										沒想到網友竟然"
html[158]="									</p>"
html[159]="									<p>"
html[160]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[161]="									</p>"
html[162]="								</div>"
html[163]="							</div>"
html[164]="						</div>"
html[165]="						<div class=\"col-md-4\">"
html[166]="							<div class=\"thumbnail\">"
html[167]="								<img alt=\"Bootstrap Thumbnail Third\" src=\"http://lorempixel.com/output/sports-q-c-600-200-1.jpg\">"
html[168]="								<div class=\"caption\">"
html[169]="									<h3>"
html[170]="										Thumbnail label"
html[171]="									</h3>"
html[172]="									"
html[173]="									<p>"
html[174]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[175]="									</p>"
html[176]="								</div>"
html[177]="							</div>"
html[178]="						</div>"
html[179]="					</div>"
html[180]="				</div>"
html[181]="				<div class=\"col-md-4\">"
html[182]="				</div>"
html[183]="			</div>"
html[184]=""
html[185]="<div class=\"row\">"
html[186]="				<div class=\"col-md-4\">"
html[187]="				</div>"
html[188]="				<div class=\"col-md-4\">"
html[189]="					<div class=\"row\">"
html[190]="						<div class=\"col-md-4\">"
html[191]="							<div class=\"thumbnail\">"
html[192]="								<img alt=\"Bootstrap Thumbnail First\" src=\"http://lorempixel.com/output/people-q-c-600-200-1.jpg\">"
html[193]="								<div class=\"caption\">"
html[194]="									<h3>"
html[195]="										Thumbnail label"
html[196]="									</h3>"
html[197]="									<p>"
html[198]="										Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit."
html[199]="									</p>"
html[200]=""
html[201]="									<p>"
html[202]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[203]="									</p>"
html[204]="								</div>"
html[205]="							</div>"
html[206]="						</div>"
html[207]="						<div class=\"col-md-4\">"
html[208]="							<div class=\"thumbnail\">"
html[209]="								<img alt=\"Bootstrap Thumbnail Second\" src=\"https://i.imgur.com/KyvRPlG.jpg\">"
html[210]="								<div class=\"caption\">"
html[211]="									<h3>"
html[212]="										Thumbnail label"
html[213]="									</h3>"
html[214]="									<p>"
html[215]="										沒想到網友竟然"
html[216]="									</p>"
html[217]="									<p>"
html[218]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[219]="									</p>"
html[220]="								</div>"
html[221]="							</div>"
html[222]="						</div>"
html[223]="						<div class=\"col-md-4\">"
html[224]="							<div class=\"thumbnail\">"
html[225]="								<img alt=\"Bootstrap Thumbnail Third\" src=\"http://lorempixel.com/output/sports-q-c-600-200-1.jpg\">"
html[226]="								<div class=\"caption\">"
html[227]="									<h3>"
html[228]="										Thumbnail label"
html[229]="									</h3>"
html[230]="									"
html[231]="									<p>"
html[232]="										<a class=\"btn btn-primary\" href=\"#\">點我看新聞</a>"
html[233]="									</p>"
html[234]="								</div>"
html[235]="							</div>"
html[236]="						</div>"
html[237]="					</div>"
html[238]="				</div>"
html[239]="				<div class=\"col-md-4\">"
html[240]="				</div>"
html[241]="			</div>"
html[242]=""
html[243]=""
html[244]="		</div>"
html[245]="	</div>"
html[246]="</div>"
html[247]=""
html[248]="    <script src=\"js/jquery.min.js\"></script>"
html[249]="    <script src=\"js/bootstrap.min.js\"></script>"
html[250]="    <script src=\"js/scripts.js\"></script>"
html[251]="  </body>"
html[252]="</html>"
